name: Package CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          - "3.12"

    steps:
      - uses: actions/checkout@v3

      - name: Python ${{ matrix.python-version }} setup
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          version: 0.6.14
          enable-cache: true
          cache-local-path: ~/.cache/uv
          cache-dependency-glob: pyproject.toml

      - name: Install package
        run: uv sync --all-extras --dev

      - name: Run ruff
        shell: bash
        run: |
          uv run ruff check .
          uv run ruff format . --check

      - name: Run mypy
        shell: bash
        run: |
          uv run mypy src --config pyproject.toml

      - name: Run pytest
        shell: bash
        run: |
          uv run pytest tests
